# Generated by Django 5.1.7 on 2025-04-17 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_client_service_quote_quoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='evening_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 1, 38, 43, 93694, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time_period',
            field=models.CharField(choices=[('standard', '8am-5pm'), ('evening', '5pm-2am'), ('night', '9pm-2am'), ('weekend', 'Weekend/Holiday')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weekend_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
