# Generated by Django 5.1.7 on 2025-04-20 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_evening_fee_alter_quote_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='invoice_number',
            field=models.CharField(default='BK0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 21, 47, 16, 842335, tzinfo=datetime.timezone.utc)),
        ),
    ]
