# Generated by Django 5.1.7 on 2025-04-20 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_invoice_number_alter_quote_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 21, 47, 50, 644723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
