# Generated by Django 5.1.7 on 2025-04-25 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quote_expires_at_alter_quote_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('author_name', models.CharField(default='Your Name', help_text='Name of the author to display', max_length=100)),
                ('content', models.TextField(help_text='HTML content with image references')),
                ('summary', models.TextField(blank=True, help_text='Short description for meta tags and previews')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('featured_image_path', models.CharField(blank=True, help_text="Path to featured image in static folder (e.g., 'blog/img1.jpg')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 1, 49, 29, 531542, tzinfo=datetime.timezone.utc)),
        ),
    ]
