# Generated by Django 5.1.7 on 2025-04-26 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_blogpost_alter_quote_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 19, 7, 49, 696668, tzinfo=datetime.timezone.utc)),
        ),
    ]
