# Generated by Django 5.1.7 on 2025-05-13 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_quote_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('business_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_position', models.CharField(blank=True, max_length=100)),
                ('visit_type', models.CharField(choices=[('COLD_VISIT', 'Cold Visit'), ('COLD_CALL', 'Cold Call'), ('FOLLOW_UP', 'Follow-up Visit'), ('NETWORKING', 'Networking Event'), ('REFERRAL', 'Referral Visit'), ('OTHER', 'Other')], max_length=20)),
                ('cards_left', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Visit',
                'verbose_name_plural': 'Business Visits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MileageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip_purpose', models.CharField(choices=[('CLIENT_VISIT', 'Client Visit'), ('PROSPECTING', 'Prospecting'), ('SUPPLIES', 'Picking up Supplies'), ('SERVICE', 'Service Call'), ('OTHER', 'Other Business Purpose')], max_length=20)),
                ('start_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mileage Entry',
                'verbose_name_plural': 'Mileage Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=800),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 0, 31, 57, 95095, tzinfo=datetime.timezone.utc)),
        ),
    ]
