# Generated by Django 5.1.7 on 2025-05-30 01:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_businessvisit_mileageentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='original_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='mileageentry',
            name='end_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999, message='Odometer reading cannot exceed 999,999')]),
        ),
        migrations.AlterField(
            model_name='mileageentry',
            name='start_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999, message='Odometer reading cannot exceed 999,999')]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 29, 1, 24, 13, 840424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('viewed', 'Viewed by Client'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('modified', 'Modified (Locked)'), ('invoice', 'Invoice')], default='draft', max_length=20),
        ),
    ]
