# Generated by Django 5.1.7 on 2025-07-03 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_quote_expires_at_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 1, 35, 7, 277834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('viewed', 'Viewed by Client'), ('quote_viewed', 'Quote Viewed by Client'), ('invoice_viewed', 'Invoice Viewed by Client'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('modified', 'Modified (Locked)'), ('invoice', 'Invoice')], default='draft', max_length=20),
        ),
    ]
